const char *parrot[] = {
":oho/-`\t\t\t\t\t",
"`mMMMMMMMMMMMNmmdhy-\t\t\t",
" dMMMMMMMMMMMMMMMMMMs`\t\t\t",
" +MMsohNMMMMMMMMMMMMMm/\t\t\t",
" .My   .+dMMMMMMMMMMMMMh.\t\t",
"  +       :NMMMMMMMMMMMMNo\t\t",
"           `yMMMMMMMMMMMMMm:\t\t",
"             /NMMMMMMMMMMMMMy`\t\t",
"              .hMMMMMMMMMMMMMN+\t\t",
"                  ``-NMMMMMMMMMd-\t",
"                     /MMMMMMMMMMMs`\t",
"                      mMMMMMMMsyNMN/\t",
"                      +MMMMMMMo  :sNh.\t",
"                      `NMMMMMMm     -o/\t",
"                       oMMMMMMM.\t",
"                       `NMMMMMM+1\t",
"                        +MMd/NMh\t",
"                         mMm -mN`\t",
"                         /MM  `h:\t",
"                          dM`   .\t",
"                          :M-\t",
"                           d:\t",
"                           -+\t",
"                            -\t"
};
